### ISSUE TITLE
code?

### ISSUE THREAD

**Issue by JimmyLopes** [RPerobeli/ElasticSearchIntro#1]
https://github.com/RPerobeli/ElasticSearchIntro/blob/b086721a3fc3acf55258c9de888b19bf51c8221f/README.md?plain=1#L1

Coloca uns codigo ai que quero acompanhar esse repo kkkk

**Comment by RPerobeli** [comment]
foi mal, esqueci kkkkk

**Comment by JimmyLopes** [comment]
acho bom mlk
Jimmy Botezine Lopes
Analista de Sistemas

phone:  32999008397
email:  ***@***.***
address:   Juiz de Fora - MG



Em qua., 17 de nov. de 2021 às 22:50, Rodrigo Perobeli Silva Costa <
***@***.***> escreveu:
